package com.denizd.cashmere.util

import androidx.annotation.DrawableRes
import androidx.annotation.StringRes
import com.denizd.cashmere.R

enum class ClothingDrawable(@StringRes val stringId: Int, @DrawableRes val drawableId: Int) {

    CAP(R.string.cap, R.drawable.cap),
    HAT(R.string.hat, R.drawable.hat),
    BOWLER_HAT(R.string.bowler_hat, R.drawable.bowler_hat),
    WINTER_HAT(R.string.winter_hat, R.drawable.winter_hat),
    GLASSES(R.string.glasses, R.drawable.glasses),
    TIE(R.string.tie, R.drawable.tie),
    BOW_TIE(R.string.bow_tie, R.drawable.bow_tie),
    SCARF(R.string.scarf, R.drawable.scarf),
    BELT(R.string.belt, R.drawable.belt),
    BRA(R.string.bra, R.drawable.bra),
    LINGERIE(R.string.lingerie, R.drawable.lingerie),
    SWIMSUIT_2(R.string.swimsuit_2, R.drawable.swimsuit_2),
    SLEEVELESS(R.string.sleeveless, R.drawable.sleeveless),
    VEST(R.string.vest, R.drawable.vest),
    SHIRT_3(R.string.shirt_3, R.drawable.shirt_3),
    POLO(R.string.polo, R.drawable.polo),
    SHIRT_2(R.string.shirt_2, R.drawable.shirt_2),
    SHIRT_1(R.string.shirt_1, R.drawable.shirt_1),
    BATHROBE(R.string.bathrobe, R.drawable.bathrobe),
    DRESS_4(R.string.dress_4, R.drawable.dress_4),
    DRESS_2(R.string.dress_2, R.drawable.dress_2),
    DRESS_3(R.string.dress_3, R.drawable.dress_3),
    DRESS_1(R.string.dress_1, R.drawable.dress_1),
    PULLOVER(R.string.pullover, R.drawable.pullover),
    SWEATSHIRT(R.string.sweatshirt, R.drawable.sweatshirt),
    JACKET_1(R.string.jacket_1, R.drawable.jacket_1),
    JACKET_3(R.string.jacket_3, R.drawable.jacket_3),
    JACKET_4(R.string.jacket_4, R.drawable.jacket_4),
    TRENCH_COAT(R.string.trench_coat, R.drawable.trench_coat),
    JACKET_2(R.string.jacket_2, R.drawable.jacket_2),
    OVERALL(R.string.overall, R.drawable.overall),
    SKIRT(R.string.skirt, R.drawable.skirt),
    UNDERPANTS(R.string.underpants, R.drawable.underpants),
    BOXERS(R.string.boxers, R.drawable.boxers),
    SWIMSUIT_1(R.string.swimsuit_1, R.drawable.swimsuit_1),
    SHORTS(R.string.shorts, R.drawable.shorts),
    JEANS(R.string.jeans, R.drawable.jeans),
    TROUSERS(R.string.trousers, R.drawable.trousers),
    SOCKS(R.string.socks, R.drawable.socks),
    SLIPPERS(R.string.slippers, R.drawable.slippers),
    HIGH_HEELS(R.string.high_heels, R.drawable.high_heel),
    SHOES(R.string.shoes, R.drawable.shoe),
    SNEAKERS_1(R.string.sneakers_1, R.drawable.sneakers_1),
    SNEAKERS_2(R.string.sneakers_2, R.drawable.sneakers_2),
    BOOTS(R.string.boots, R.drawable.boot),
    BACKPACK(R.string.backpack, R.drawable.backpack),
    PURSE_1(R.string.purse_1, R.drawable.purse_1),
    PURSE_2(R.string.purse_2, R.drawable.purse_2),
    SUITCASE(R.string.suitcase, R.drawable.suitcase),
    ;
}