package com.denizd.cashmere.util

import androidx.annotation.DrawableRes
import com.denizd.cashmere.R

enum class ClothingDrawable(@DrawableRes val drawableId: Int) {
    BACKPACK(R.drawable.backpack),
    BATHROBE(R.drawable.bathrobe),
    BELT(R.drawable.belt),
    BOOT(R.drawable.boot),
    BOW_TIE(R.drawable.bow_tie),
    BOWLER_HAT(R.drawable.bowler_hat),
    BOXERS(R.drawable.boxers),
    BRA(R.drawable.bra),
    CAP(R.drawable.cap),
    DRESS(R.drawable.dress),
    DRESS_1(R.drawable.dress_1),
    DRESS_2(R.drawable.dress_2),
    DRESS_3(R.drawable.dress_3),
    GLASSES(R.drawable.glasses),
    HAT(R.drawable.hat),
    HIGH_HEEL(R.drawable.high_heel),
    JACKET(R.drawable.jacket),
    JACKET_1(R.drawable.jacket_1),
    JACKET_2(R.drawable.jacket_2),
    JACKET_3(R.drawable.jacket_3),
    JEANS(R.drawable.jeans),
    LINGERIE(R.drawable.lingerie),
    OVERALL(R.drawable.overall),
    POLO(R.drawable.polo),
    PULLOVER(R.drawable.pullover),
    PURSE(R.drawable.purse),
    PURSE_1(R.drawable.purse_1),
    SCARF(R.drawable.scarf),
    SHIRT(R.drawable.shirt),
    SHIRT_1(R.drawable.shirt_1),
    SHIRT_2(R.drawable.shirt_2),
    SHOE(R.drawable.shoe),
    SHORTS(R.drawable.shorts),
    SKIRT(R.drawable.skirt),
    SLEEVELESS(R.drawable.sleeveless),
    SLIPPERS(R.drawable.slippers),
    SNEAKERS(R.drawable.sneakers),
    SNEAKERS_1(R.drawable.sneakers_1),
    SOCKS(R.drawable.socks),
    SUITCASE(R.drawable.suitcase),
    SWEATSHIRT(R.drawable.sweatshirt),
    SWIMSUIT(R.drawable.swimsuit),
    SWIMSUIT_1(R.drawable.swimsuit_1),
    TIE(R.drawable.tie),
    TRENCH_COAT(R.drawable.trench_coat),
    TRENCH_COAT_1(R.drawable.trench_coat_1),
    TROUSERS(R.drawable.trousers),
    UNDERPANTS(R.drawable.underpants),
    VEST(R.drawable.vest),
    WINTER_HAT(R.drawable.winter_hat),
    ;
}